name: Deploy to EC2
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: 
      - ubuntu-latest
      - label-test-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH into EC2
#        uses: appleboy/ssh-action@master
        run: |
            cd /home/ubuntu/mallia
            ls
            git pull origin main
            docker-compose up -d
