name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: 44.211.150.154
          username: ubuntu
          key: ${{ secrets.SECRETS_KEY_NAME}}
          port: 22
          script: |
            cd /home/ubuntu/mallia
            git pull origin main
      - name: Start Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 44.211.150.154
          username: ubuntu
          key: ${{ secrets.SECRETS_KEY_NAME}}
          port: 22
          script: |
            cd /home/ubuntu/mallia
            docker-compose up -d 
            
